spring:
  application:
    name: Stock-Price-API  datasource:    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin  h2:    console:      enabled: true
    
server:  port: 1111
  